'use client';

import Link from 'next/link'; import { useCallback, useEffect, useRef, useState } from 'react';
import type { Chapter, ReaderSettings } from '../lib/types';
import type { ReaderState } from '../lib/storage';
import { defaultState, loadReaderState, saveReaderState } from '../lib/storage';
import { book, chapters, volumes } from '../lib/data';
import SearchDialog from './SearchDialog'; import SettingsDrawer from './SettingsDrawer'; import SiteHeader from './SiteHeader';

export default function ReaderClient({ chapter }: { chapter: Chapter }) {
  const [state, setState] = useState<ReaderState>(defaultState); const [ready, setReady] = useState(false); const [searchOpen, setSearchOpen] = useState(false); const [settingsOpen, setSettingsOpen] = useState(false); const [tocOpen, setTocOpen] = useState(false); const [focusMode, setFocusMode] = useState(false); const [speaking, setSpeaking] = useState(false); const [progress, setProgress] = useState(0); const [breakNotice, setBreakNotice] = useState(false); const rulerRef = useRef<HTMLDivElement>(null);
  const volume = volumes.find((item) => item.number === chapter.volumeNumber)!; const prev = chapter.number > 1 ? chapter.number - 1 : null; const next = chapter.number < book.totalChapters ? chapter.number + 1 : null;
  useEffect(() => { const timer = window.setTimeout(() => { const loaded = loadReaderState(); const readChapters = loaded.readChapters.includes(chapter.number) ? loaded.readChapters : [...loaded.readChapters, chapter.number].sort((a,b) => a-b); const nextState = { ...loaded, lastChapter:chapter.number, readChapters }; setState(nextState); setReady(true); requestAnimationFrame(() => window.scrollTo(0, nextState.scrollPositions[String(chapter.number)] ?? 0)); }, 0); return () => window.clearTimeout(timer); }, [chapter.number]);
  useEffect(() => { if (ready) saveReaderState(state); }, [ready, state]);
  useEffect(() => { const update = () => { const max = document.documentElement.scrollHeight - window.innerHeight; setProgress(max > 0 ? Math.min(100, Math.round((window.scrollY / max) * 100)) : 0); setState((current) => ({ ...current, scrollPositions:{ ...current.scrollPositions, [String(chapter.number)]:window.scrollY } })); }; let timer = 0; const throttled = () => { window.clearTimeout(timer); timer = window.setTimeout(update, 120); }; window.addEventListener('scroll', throttled, { passive:true }); return () => { window.removeEventListener('scroll', throttled); window.clearTimeout(timer); }; }, [chapter.number]);
  useEffect(() => { const shortcut = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setSearchOpen(true); } if (event.key.toLowerCase() === 't' && !searchOpen) setTocOpen((open) => !open); if (event.key === 'ArrowLeft' && prev && !searchOpen) location.href = `/book/${book.slug}/chapter/${prev}`; if (event.key === 'ArrowRight' && next && !searchOpen) location.href = `/book/${book.slug}/chapter/${next}`; }; window.addEventListener('keydown', shortcut); return () => window.removeEventListener('keydown', shortcut); }, [next, prev, searchOpen]);
  useEffect(() => { if (!state.settings.breakReminder) return; const timer = window.setTimeout(() => setBreakNotice(true), 20 * 60 * 1000); return () => window.clearTimeout(timer); }, [state.settings.breakReminder]);
  useEffect(() => { if (!state.settings.readingRuler) return; const move = (event: MouseEvent) => { if (rulerRef.current) rulerRef.current.style.transform = `translateY(${event.clientY - 28}px)`; }; window.addEventListener('mousemove', move); return () => window.removeEventListener('mousemove', move); }, [state.settings.readingRuler]);
  const closeSearch = useCallback(() => setSearchOpen(false), []); const closeSettings = useCallback(() => setSettingsOpen(false), []); const updateSettings = (settings: ReaderSettings) => setState((current) => ({ ...current, settings })); const bookmarked = state.bookmarks.includes(chapter.number);
  const toggleBookmark = () => setState((current) => ({ ...current, bookmarks:bookmarked ? current.bookmarks.filter((item) => item !== chapter.number) : [...current.bookmarks, chapter.number].sort((a,b) => a-b) }));
  const speak = () => { if (!('speechSynthesis' in window)) return; if (speaking) { window.speechSynthesis.cancel(); setSpeaking(false); return; } const utterance = new SpeechSynthesisUtterance(`${chapter.number}. ${chapter.title}. ${chapter.content.join(' ')}`); utterance.lang = 'th-TH'; utterance.onend = () => setSpeaking(false); window.speechSynthesis.speak(utterance); setSpeaking(true); };
  const settings = state.settings; const articleClass = `reader-paper width-${settings.width} font-${settings.font} align-${settings.align} spacing-${settings.spacing}`;
  const volumeChapters = chapters.filter((entry) => entry.volumeNumber === volume.number);
  return (
    <main className={`reader-shell ${focusMode ? 'focus-mode' : ''}`}>
      <SiteHeader compact onSearch={() => setSearchOpen(true)} onSettings={() => setSettingsOpen(true)} /><div className="reading-progress" aria-label={`ความคืบหน้าหน้า ${progress}%`}><span style={{ width:`${progress}%` }} /></div>
      <div className="reader-context"><Link href="/">‹ ชั้นหนังสือ</Link><span>เล่ม {chapter.volumeNumber} / {chapter.number}. {chapter.title}</span><div><button type="button" onClick={() => setTocOpen(true)} aria-label="ไปยังตอนที่ต้องการ">ไปตอน</button><button type="button" onClick={() => setFocusMode((active) => !active)} aria-pressed={focusMode}>Focus</button><button type="button" onClick={speak} aria-pressed={speaking}>{speaking ? 'หยุด' : 'ฟัง'}</button><button type="button" onClick={toggleBookmark} aria-label={bookmarked ? 'นำที่คั่นหน้าออก' : 'คั่นหน้าตอนนี้'} aria-pressed={bookmarked}>{bookmarked ? '◆' : '◇'}</button></div></div>
      <article className={articleClass} style={{ fontSize:`${settings.fontSize}px`, lineHeight:settings.lineHeight }}>
        <div className="reader-selects" aria-label="เลือกเล่มและตอน"><label>เล่ม<select value={volume.number} onChange={(event) => { const selected = volumes.find((item) => item.number === Number(event.target.value)); if (selected) location.href = `/book/${book.slug}/chapter/${selected.firstChapter}`; }}>{volumes.map((item) => <option key={item.id} value={item.number}>เล่ม {item.number} · {item.title}</option>)}</select></label><label>ตอน<select value={chapter.number} onChange={(event) => { location.href = `/book/${book.slug}/chapter/${event.target.value}`; }}>{volumeChapters.map((entry) => <option key={entry.id} value={entry.number}>{entry.number}. {entry.title}</option>)}</select></label></div>
        <div className="source-note"><strong>ต้นฉบับอ้างอิง</strong><span>{chapter.sourceFile}</span><span>หน้า {chapter.pdfStartPage}–{chapter.pdfEndPage} จาก {chapter.totalPdfPages}</span></div>
        {settings.showChapterArt && <div className={`chapter-art tone-${volume.tone}`} aria-label={`ภาพบรรยากาศเปิดตอน ${chapter.number}`}><span>VOLUME {String(volume.number).padStart(2,'0')}</span><strong>{String(chapter.number).padStart(4,'0')}</strong><small>HOR AKSARA ARCHIVE</small></div>}<header className="chapter-head"><p>เล่ม {String(volume.number).padStart(2,'0')} · ตอนที่ {chapter.number} จาก {book.totalChapters}</p><h1>{chapter.number}. {chapter.title}</h1><span>เวลาอ่านประมาณ {Math.max(3, chapter.content.length * 2)} นาที</span></header><div className="chapter-content">{chapter.content.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><div className="chapter-end"><span>จบตอน</span><nav aria-label="เปลี่ยนตอน">{prev ? <a href={`/book/${book.slug}/chapter/${prev}`}>← ตอนก่อนหน้า</a> : <span />}{next ? <a href={`/book/${book.slug}/chapter/${next}`}>ตอนถัดไป →</a> : <Link href="/">กลับชั้นหนังสือ</Link>}</nav></div>
      </article>
      <div className="chapter-slider"><span>{volume.firstChapter}</span><input aria-label="เลือกตอนในเล่ม" type="range" min={volume.firstChapter} max={volume.lastChapter} value={chapter.number} onChange={(event) => { location.href = `/book/${book.slug}/chapter/${event.target.value}`; }} /><span>{volume.lastChapter}</span></div>
      <nav className="reader-float" aria-label="ทางลัดการอ่าน">{prev ? <a href={`/book/${book.slug}/chapter/${prev}`} aria-label="ตอนก่อนหน้า">↑</a> : <span /> }<button type="button" onClick={() => setTocOpen(true)} aria-label="เปิดสารบัญ">☷</button>{next ? <a href={`/book/${book.slug}/chapter/${next}`} aria-label="ตอนถัดไป">↓</a> : <span /> }<button className="optional-float" type="button" onClick={() => window.scrollTo({ top:0, behavior:'smooth' })} aria-label="กลับด้านบน">⌃</button></nav>
      {settings.readingRuler && <div ref={rulerRef} className="reading-ruler" aria-hidden="true" />}
      <aside className={`toc-drawer ${tocOpen ? 'open' : ''}`} aria-hidden={!tocOpen}><div className="drawer-head"><div><p className="eyebrow">นำทาง</p><h2>สารบัญ</h2></div><button type="button" onClick={() => setTocOpen(false)} aria-label="ปิดสารบัญ">×</button></div>{volumes.map((item) => <section key={item.id}><h3>เล่ม {item.number} · {item.title}</h3>{chapters.filter((entry) => entry.volumeNumber === item.number).map((entry) => <a className={entry.number === chapter.number ? 'current' : ''} href={`/book/${book.slug}/chapter/${entry.number}`} key={entry.id}><span>{entry.number}</span>{entry.title}</a>)}</section>)}</aside>
      <SearchDialog open={searchOpen} onClose={closeSearch} chapters={chapters} /><SettingsDrawer open={settingsOpen} onClose={closeSettings} value={settings} onChange={updateSettings} />{(tocOpen || settingsOpen) && <button className="drawer-scrim" type="button" onClick={() => { setTocOpen(false); setSettingsOpen(false); }} aria-label="ปิดแผงด้านข้าง" />}
      {breakNotice && <div className="break-notice" role="status"><strong>พักสายตาสักครู่ไหม</strong><p>มองไกลประมาณ 20 วินาที แล้วค่อยกลับมาอ่านต่อ</p><button type="button" onClick={() => setBreakNotice(false)}>รับทราบ</button></div>}
    </main>
  );
}
